name: BreakerConfiguration
description: Switching arrangement for bay.
attributes:
- name: singleBreaker
  description: Single breaker.
- name: breakerAndAHalf
  description: Breaker and a half.
- name: doubleBreaker
  description: Double breaker.
- name: noBreaker
  description: No breaker.