name: BusbarConfiguration
description: Busbar layout for bay.
attributes:
- name: singleBus
  description: Single bus.
- name: doubleBus
  description: Double bus.
- name: mainWithTransfer
  description: Main bus with transfer bus.
- name: ringBus
  description: Ring bus.