name: ExpectedEnergyValues
description: Model Expected Energy from Market Clearing.
attributes:
- name: energyTypeCode
  type: String
- name: expectedMwh
  type: Float
associations:
- source: ExpectedEnergyValues
  target: ExpectedEnergy
  sourceCardinality: 1..*
  targetCardinality: "1"
  sourceName: ExpectedEnergyValues
  targetName: ExpectedEnergy
- source: ExpectedEnergyValues
  target: RegisteredResource
  sourceCardinality: 0..*
  targetCardinality: 0..1
  sourceName: ExpectedEnergyValues
  targetName: RegisteredResource