name: ConfigurationEvent
description: Used to report details on creation, change or deletion of an entity or its configuration.
attributes:
- name: effectiveDateTime
  type: DateTime
  description: Date and time this event has or will become effective.
- name: modifiedBy
  type: String
  description: Source/initiator of modification.
- name: remark
  type: String
  description: Free text remarks.
ancestors:
- ActivityRecord
associations:
- source: ConfigurationEvent
  target: FaultCauseType
  sourceCardinality: 0..*
  targetCardinality: "1"
  sourceName: ConfigurationEvent
  targetName: FaultCauseType
- source: ConfigurationEvent
  target: Document
  sourceCardinality: 0..*
  targetCardinality: 0..1
  sourceName: ConfigurationEvents
  sourceDescription: All configuration events created for this document.
  targetName: ChangedDocument
  targetDescription: Document whose change resulted in this configuration event.
- source: ConfigurationEvent
  target: UsagePoint
  sourceCardinality: 0..*
  targetCardinality: 0..1
  sourceName: ConfigurationEvents
  sourceDescription: All configuration events created for this usage point.
  targetName: ChangedUsagePoint
  targetDescription: Usage point whose change resulted in this configuration event.
- source: ConfigurationEvent
  target: OrganisationRole
  sourceCardinality: 0..*
  targetCardinality: 0..1
  sourceName: ConfigurationEvents
  sourceDescription: All configuration events created for this organisation role.
  targetName: ChangedOrganisationRole
  targetDescription: Organisation role whose change resulted in this configuration event.
- source: ConfigurationEvent
  target: Asset
  sourceCardinality: 0..*
  targetCardinality: 0..1
  sourceName: ConfigurationEvents
  sourceDescription: All configuration events created for this asset.
  targetName: ChangedAsset
  targetDescription: Asset whose change resulted in this configuration event.
- source: ConfigurationEvent
  target: Location
  sourceCardinality: 0..*
  targetCardinality: 0..1
  sourceName: ConfigurationEvents
  sourceDescription: All configuration events created for this location.
  targetName: ChangedLocation
  targetDescription: Location whose change resulted in this configuration event.
- source: ConfigurationEvent
  target: PersonRole
  sourceCardinality: 0..*
  targetCardinality: 0..1
  sourceName: ConfigurationEvents
  sourceDescription: All configuration events created for this person role.
  targetName: ChangedPersonRole
  targetDescription: Person role whose change resulted in this configuration event.
- source: ConfigurationEvent
  target: ServiceCategory
  sourceCardinality: 0..*
  targetCardinality: 0..1
  sourceName: ConfigurationEvents
  sourceDescription: All configuration events created for this service category.
  targetName: ChangedServiceCategory
  targetDescription: Service category whose change resulted in this configuration event.
- source: ConfigurationEvent
  target: PowerSystemResource
  sourceCardinality: 0..*
  targetCardinality: 0..1
  sourceName: ConfigurationEvent
  targetName: PowerSystemResource