name: CombinedCycleLogicalConfiguration
description: "Logical Configuration of a Combined Cycle plant.\n\nOperating Combined Cycle Plant (CCP) configurations are\
  \ represented as Logical CCP Resources. Logical representation shall be used for Market applications to optimize and control\
  \ Market Operations. Logical representation is also necessary for controlling the number of CCP configurations and to temper\
  \ performance issues that may otherwise occur. \n\nFor example,(2CT configuration),(1CT + 1ST configuration) are examples\
  \ of logical configuration, without specifying the specific CT and ST participating in the configuration."
ancestors:
- IdentifiedObject
associations:
- source: CombinedCycleLogicalConfiguration
  target: MktCombinedCyclePlant
  sourceCardinality: 1..*
  sourceName: CombinedCycleLogicalConfiguration
  targetCardinality: 0..1
  targetName: MktCombinedCyclePlant
- source: CombinedCycleLogicalConfiguration
  target: CombinedCycleConfiguration
  sourceCardinality: 0..1
  sourceName: CombinedCycleLogicalConfiguration
  targetCardinality: 1..*
  targetName: CombinedCycleConfiguration