name: CombinedCycleConfigurationMember
description: Configuration Member of CCP Configuration.
attributes:
- name: primary
  type: Boolean
  description: primary configuration.
- name: steam
  type: Boolean
  description: Steam plant.
ancestors:
- IdentifiedObject
associations:
- source: CombinedCycleConfigurationMember
  target: MktThermalGeneratingUnit
  sourceCardinality: 0..*
  sourceName: CombinedCycleConfigurationMember
  targetCardinality: "1"
  targetName: MktThermalGeneratingUnit
- source: CombinedCycleConfigurationMember
  target: CombinedCycleConfiguration
  sourceCardinality: 0..*
  sourceName: CombinedCycleConfigurationMember
  targetCardinality: "1"
  targetName: CombinedCycleConfiguration