name: CombinedCycleConfigurationMember
description: Configuration Member of CCP Configuration.
attributes:
- name: primary
  type: Boolean
  description: primary configuration.
- name: steam
  type: Boolean
  description: Steam plant.
ancestors:
- IdentifiedObject
associations:
- source: CombinedCycleConfigurationMember
  target: MktThermalGeneratingUnit
  sourceCardinality: 0..*
  targetCardinality: "1"
  sourceName: CombinedCycleConfigurationMember
  targetName: MktThermalGeneratingUnit
- source: CombinedCycleConfiguration
  target: CombinedCycleConfigurationMember
  sourceCardinality: "1"
  targetCardinality: 0..*
  sourceName: CombinedCycleConfiguration
  targetName: CombinedCycleConfigurationMember