name: EnvironmentalAnalog
description: Analog (float) measurement of relevance in the environmental domain.
ancestors:
- Analog
descendents:
- GeosphericAnalog
- AtmosphericAnalog
- HydrosphericAnalog
- SpaceAnalog
associations:
- source: EnvironmentalAnalog
  target: EnvironmentalInformation
  sourceCardinality: 0..*
  targetCardinality: 0..1
  sourceName: EnvironmentalAnalog
  sourceDescription: Environmental analog associated with this observation or forecast.
  targetName: EnvironmentalInformation
  targetDescription: Observation or forecast with which this environmental analog measurement is associated.
- source: EnvironmentalAnalog
  target: ClassificationCondition
  sourceCardinality: 0..*
  targetCardinality: 0..1
  sourceName: EnvironmentalAnalog
  sourceDescription: Analog which contributes to the definition of this classification condition.
  targetName: ClassificationCondition
  targetDescription: Classification condition which this analog helps define.
- source: EnvironmentalAnalog
  target: ReportingCapability
  sourceCardinality: 0..*
  targetCardinality: 0..1
  sourceName: EnvironmentalAnalog
  sourceDescription: One of the environmental value sets expressing one of the reporting capabilities.
  targetName: ReportingCapability
  targetDescription: The reporting capability this environmental value set helps define.
- source: EnvironmentalAnalog
  target: EnvironmentalMonitoringStation
  sourceCardinality: 0..*
  targetCardinality: 0..1
  sourceName: EnvironmentalAnalog
  sourceDescription: Environmental analog measurement provided by this monitoring station.
  targetName: EnvironmentalMonitoringStation
  targetDescription: Monitoring station which provides this environmental analog measurement.