name: EnvironmentalDataAuthority
description: An entity defining classifications or categories of environmental information, like phenomena or alerts.
ancestors:
- OrganisationRole
associations:
- source: EnvironmentalDataAuthority
  target: AlertTypeList
  sourceCardinality: 0..1
  sourceName: EnvironmentalDataAuthority
  sourceDescription: The environmental data authority responsible for publishing this list of alert types.
  targetCardinality: 0..*
  targetName: AlertTypeList
  targetDescription: A specific version of a list of alerts published by this environmental data authority.
- source: EnvironmentalDataAuthority
  target: PhenomenonClassification
  sourceCardinality: 0..1
  sourceName: EnvironmentalDataAuthority
  sourceDescription: Authority defining this environmental phenomenon.
  targetCardinality: 0..*
  targetName: PhenomenonClassification
  targetDescription: Phenomenon classification defined by this environmental data authority.