name: EnvironmentalLocationType
description: Type of environmental location. Used when an environmental alert or phenomenon has multiple locations associated
  with it.
attributes:
- name: kind
  type: LocationKind
  description: The kind of location. Typical values might be center, extent, primary, secondary, etc.
associations:
- source: EnvironmentalLocationType
  target: Location
  sourceCardinality: 0..*
  targetCardinality: 0..1
  sourceName: EnvironmentalLocationKind
  sourceDescription: Kind of environmental location which this location is.
  targetName: Location
  targetDescription: Location of this instance of ths kind of environmental location.
- source: EnvironmentalLocationType
  target: EnvironmentalAlert
  sourceCardinality: 1..*
  targetCardinality: 0..*
  sourceName: EnvironmentalLocationKind
  sourceDescription: Type of location to which this environmental alert applies.
  targetName: EnvironmentalAlert
  targetDescription: Environmental alert applying to location of this type.
- source: EnvironmentalLocationType
  target: EnvironmentalPhenomenon
  sourceCardinality: 0..*
  targetCardinality: 0..*
  sourceName: EnvironmentalLocationKind
  sourceDescription: Location of relevance to this environmental phenomenon.
  targetName: EnvironmentalPhenomenon
  targetDescription: Environmental phenomenon for which this location is of relevance.