name: EnvironmentalDataAuthority
description: An entity defining classifications or categories of environmental information, like phenomena or alerts.
ancestors:
- OrganisationRole
associations:
- source: AlertTypeList
  target: EnvironmentalDataAuthority
  sourceCardinality: 0..*
  targetCardinality: 0..1
  sourceName: AlertTypeList
  sourceDescription: A specific version of a list of alerts published by this environmental data authority.
  targetName: EnvironmentalDataAuthority
  targetDescription: The environmental data authority responsible for publishing this list of alert types.
- source: PhenomenonClassification
  target: EnvironmentalDataAuthority
  sourceCardinality: 0..*
  targetCardinality: 0..1
  sourceName: PhenomenonClassification
  sourceDescription: Phenomenon classification defined by this environmental data authority.
  targetName: EnvironmentalDataAuthority
  targetDescription: Authority defining this environmental phenomenon.