name: BreakerApplicationKind
description: |-
  Classifications of network roles in which breakers can be deployed. The classifications are intended to reflect both criticality of breaker in network operations and typical usage experienced by breaker.
  Note: This enumeration provides essential information to asset health analytics. The existing list is a starting point and is anticipated to be fleshed out further as requirements are better understood (PAB 2016/01/09).
attributes:
- name: capacitorOrReactorBankBreaker
  description: Capacitor or reactor breaker.
- name: busBreaker
  description: Bus breaker.
- name: busTieBreaker
  description: Bus tie breaker.
- name: feederBreaker
  description: Feeder breaker.
- name: stepUpTransformerBreakerHydro
  description: Step-up transformer breaker for hydro generator.
- name: stepUpTransformerBreakerFossil
  description: Step-up transformer breaker for fossil generator.
- name: stepUpTransformerBreakerNuclear
  description: Step-up transformer breaker for nuclear generator.
- name: stepUpTransformerBreakerPumpedStorage
  description: Step-up transformer breaker for pumped storage.
- name: substationTransformerBreaker
  description: Substation transformer breaker.
- name: transmissionFlowGateLineBreaker
  description: Transmission flow gate line breaker.
- name: transmissionLineBreaker
  description: Transmission line breaker.
- name: transmissionTieLineBreaker
  description: Transmission tie line breaker.
- name: spare
  description: Spare breaker.
- name: other
  description: Other type of breaker application.