name: TransformerApplicationKind
description: |-
  Classifications of network roles in which transformers can be deployed. The classifications are intended to reflect both criticality of transformer in network operations and typical usage experienced by transformer.
  Note: This enumeration provides essential information to asset health analytics. The existing list is a starting point and is anticipated to be fleshed out further as requirements are better understood (PAB 2016/01/09).
attributes:
- name: transmissionBusToBus
  description: Transformer between bus at one transmission voltage level and a bus at another transmission voltage level.
- name: transmissionBusToDistribution
  description: Transformer between bus at transmission voltage level and bus at distribution voltage level.
- name: generatorStepUp
  description: Transformer is generator step-up transformer.
- name: distribution
  description: Transformer between one distribution voltage level and another distribution voltage level.