name: EnvironmentalMonitoringStation
description: An environmental monitoring station, examples of which could be a weather station or a seismic monitoring station.
attributes:
- name: dstObserved
  type: Boolean
  description: Whether this station is currently reporting using daylight saving time.  Intended to aid a utility Weather
    Service in interpreting information coming from a station and has no direct relationship to the manner in which time is
    expressed in EnvironmentalValueSet.
- name: isNetworked
  type: Boolean
  description: Indication that station is part of a network of stations used to monitor weather phenomena covering a large
    geographical area.
- name: timeZoneOffset
  type: Minutes
  description: |-
    The time offset from UTC (a.k.a. GMT) configured in the station "clock", not (necessarily) the time zone in which the station is physically located.
    This attribute exists to support management of utility monitoring stations and has no direct relationship to the manner in which time is expressed in EnvironmentalValueSet.
ancestors:
- IdentifiedObject
associations:
- source: EnvironmentalMonitoringStation
  target: Location
  sourceCardinality: 0..*
  targetCardinality: 0..1
  sourceName: EnvironmentalMonitoringStation
  sourceDescription: Monitoring station located at this location.
  targetName: Location
  targetDescription: Location of this monitoring station.
- source: EnvironmentalMonitoringStation
  target: UsagePoint
  sourceCardinality: 0..1
  targetCardinality: 0..*
  sourceName: EnvironmentalMonitoringStation
  targetName: UsagePoint
- source: EnvironmentalAnalog
  target: EnvironmentalMonitoringStation
  sourceCardinality: 0..*
  targetCardinality: 0..1
  sourceName: EnvironmentalAnalog
  sourceDescription: Environmental analog measurement provided by this monitoring station.
  targetName: EnvironmentalMonitoringStation
  targetDescription: Monitoring station which provides this environmental analog measurement.
- source: TimeSeries
  target: EnvironmentalMonitoringStation
  sourceCardinality: 0..*
  targetCardinality: 0..*
  sourceName: TimeSeries
  targetName: EnvironmentalMonitoringStation
- source: ReportingCapability
  target: EnvironmentalMonitoringStation
  sourceCardinality: 0..*
  targetCardinality: "1"
  sourceName: ReportingCapability
  sourceDescription: One of the reporting capabilities of this monitoring station.
  targetName: EnvironmentalMonitoringStation
  targetDescription: The environmental monitoring station to which this set of reporting capabilities belong.