name: EnvironmentalMonitoringStation
description: An environmental monitoring station, examples of which could be a weather station or a seismic monitoring station.
attributes:
- name: dstObserved
  type: Boolean
  description: Whether this station is currently reporting using daylight saving time.  Intended to aid a utility Weather
    Service in interpreting information coming from a station and has no direct relationship to the manner in which time is
    expressed in EnvironmentalValueSet.
- name: isNetworked
  type: Boolean
  description: Indication that station is part of a network of stations used to monitor weather phenomena covering a large
    geographical area.
- name: timeZoneOffset
  type: Minutes
  description: |-
    The time offset from UTC (a.k.a. GMT) configured in the station "clock", not (necessarily) the time zone in which the station is physically located.
    This attribute exists to support management of utility monitoring stations and has no direct relationship to the manner in which time is expressed in EnvironmentalValueSet.
ancestors:
- IdentifiedObject
associations:
- source: EnvironmentalMonitoringStation
  target: Location
  sourceCardinality: 0..*
  sourceName: EnvironmentalMonitoringStation
  sourceDescription: Monitoring station located at this location.
  targetCardinality: 0..1
  targetName: Location
  targetDescription: Location of this monitoring station.
- source: EnvironmentalMonitoringStation
  target: UsagePoint
  sourceCardinality: 0..1
  sourceName: EnvironmentalMonitoringStation
  targetCardinality: 0..*
  targetName: UsagePoint
- source: EnvironmentalMonitoringStation
  target: EnvironmentalAnalog
  sourceCardinality: 0..1
  sourceName: 0..*
  sourceDescription: EnvironmentalMonitoringStation
  targetCardinality: Monitoring station which provides this environmental analog measurement.
  targetName: EnvironmentalAnalog
  targetDescription: Environmental analog measurement provided by this monitoring station.
- source: EnvironmentalMonitoringStation
  target: TimeSeries
  sourceCardinality: 0..*
  sourceName: 0..*
  sourceDescription: EnvironmentalMonitoringStation
  targetName: TimeSeries
- source: EnvironmentalMonitoringStation
  target: ReportingCapability
  sourceCardinality: "1"
  sourceName: 0..*
  sourceDescription: EnvironmentalMonitoringStation
  targetCardinality: The environmental monitoring station to which this set of reporting capabilities belong.
  targetName: ReportingCapability
  targetDescription: One of the reporting capabilities of this monitoring station.